name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]   # 필요하면 브랜치를 바꾸세요

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1) 소스 체크아웃
    - uses: actions/checkout@v4

    # 2) gcloud CLI 세팅
    - uses: google-github-actions/setup-gcloud@v2.1.4   # 최신 안정판 :contentReference[oaicite:0]{index=0}
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # 3) Artifact Registry 로그인
    - name: Authorize Docker to push
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    # 4) 이미지 빌드 & 푸시
    - name: Build and push image
      run: |
        IMAGE="asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/starful-site"
        docker build -t $IMAGE .
        docker push $IMAGE

    # 5) Cloud Run 배포
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy starful-site \
          --image "asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/starful-site" \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated

