name: Deploy to Cloud Run
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth to GCP
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build and Push Image
      run: |
        IMAGE="asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/starful-site:${{ github.sha }}"
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy starful-site \
          --image "asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/starful-site:${{ github.sha }}" \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated

